### ISSUE TITLE
Change hostname for an existing instance

### ISSUE THREAD

**Issue by hatxor** [GoogleCloudPlatform/chef-google-compute#1]
Hi,

We're provising gc instances with chef. The issue is, when we reboot an instance, this recover the hostname and fqdn of the google compute engine config, instead keep ours.

The question then is: How we can do this changes permanent or how we can change the hostname through chef in GCE?

Thanks!

**Comment by nelsonjr** [comment]
Hi Andrés,

Setting the computer hostname can happen in various ways, and it is OS specific. The most common way it gets set is by the DHCP server that provides the IP address to the machine.

For example in CentOS you can set HOSTNAME in the /etc/sysconfig/network file. That would make the host name the official name for the machine.

That leaves the DHCP client messing with the host name. There are various ways to accomplish that, and I'll list a few possibilities:

In CentOS you can specify DHCP_HOSTNAME in the /etc/sysconfig/network-scripts/ifcfg-eth0. That would make the "ifup" script honor the name specified there.

GCP today uses dhclient to provide IP address to the machine, so you can also do it /etc/dhclient.conf:

interface "eth0"  
{    
  supersede host-name "my.host.name";  
}

There may be other ways but those are the ones that come to mind. Also they are slightly different (the DHCP_HOSTNAME part) for Debian/Ubuntu.

Let me know if that solved your issue. Regards!

**Comment by hatxor** [comment]
Hi Nelson,

Thank you for your quick reply!

We already changed the host and the hostname files, but after reboot, this  change again to the google one.

We're using the cookbook "hostname", which already works in other environments, but not here, so I think GCE is overwriting it in each reboot. 

How can avoid that or change it in google with Chef?

Thank you again!

**Comment by nelsonjr** [comment]
Hi,

Sorry for the delayed reply. I missed that the issue was not resolved.

Did you try to use the `/etc/dhclient.conf` update I provided? Do you mean it did not work? Try to not run Chef on boot, set the supersede option and let me know if that worked. I just tried on a brand new Ubuntu image and it works:

```
root@instance-test-2:~# grep this-is-us /etc/dhcp/dhclient.conf 
supersede host-name "this-is-us.acme.com";
root@instance-test-2:~# systemctl restart networking
root@instance-test-2:~# hostname
this-is-us
root@instance-test-2:~# hostname -f
this-is-us.acme.com
root@instance-test-2:~# logout
nelsona@instance-test-2:/etc/dhcp$ sudo -i
root@this-is-us:~# 
```

**Comment by erjohnso** [comment]
I suspect this is a conflict with the Google agents re-setting the hostname (either periodically, or on reboot when the google startup scripts run).

**Comment by jnassern83** [comment]
ya every time i change the host name from WHM panel it's again after sometime back to same host name in GC.

**Comment by kperrow** [comment]
> ya every time i change the host name from WHM panel it's again after sometime back to same host name in GC.

Hi,
I have installed heaps of WHMC cPanel servers on Google Cloud before they even had their image on Marketplace and can confirm it does keep overriding writing the hostname on each reboot. There is nothing on WHM/cPanel panel side that can be done, Google will keep overriding your settings on each reboot.
This is an issue on Google side and you have to set the hostname manually - Luckily it's an easy fix.... 

**For Centos:**
cPanel recommends running this script, just need to change the hostname.example.com to your actual hostname.

mkdir -p /etc/dhcp/dhclient-exit-hooks.d/ && echo -ne '#!/bin/sh\nhostname hostname.example.com\n/scripts/fixetchosts\n' > /etc/dhcp/dhclient-exit-hooks.d/zzz-set-hostname.sh && chmod +x /etc/dhcp/dhclient-exit-hooks.d/zzz-set-hostname.sh

Or how I do it and works perfectly well -  ( Same for below you just need to change the ops.averste.com to your actual hostname. )

sudo -s 
nano /etc/dhcp/dhclient-exit-hooks.d/
added
#!/bin/sh
hostname ops.averste.com
/scripts/fixetchosts
Then save to set-hostname.sh

Then go back to check it had saved
/etc/dhcp/dhclient-exit-hooks.d/set-hostname.sh

And its should be showing
#!/bin/sh
hostname ops.averste.com
/scripts/fixetchosts

If it's not showing when you check /etc/dhcp/dhclient-exit-hooks.d/set-hostname.sh
The simply re-add it but directly to set-hostname.sh as you have already created the path above so run:
nano /etc/dhcp/dhclient-exit-hooks.d/set-hostname.sh
And – re-enter it and save
#!/bin/sh
hostname ops.averste.com
/scripts/fixetchosts

Then check again but it should all be working fine 😊

**For Ubuntu:**
Run 
sudo -s
hostnamectl set-hostname ops.averste.com

Then edit the /etc/hosts to add your server ip and hostname

127.0.0.1   localhost
10.20.30.40   ops.averste.com 

and save 😊

Then
nano /etc/cloud/cloud.cfg
Scroll down to preserve_hostname and change it from False to True.

Reboot and it should all be working – you can verify by running after rebooting
Sudo -s
hostnamectl
and it should return below with your new hostname

Static hostname: 	ops.averste.com 
Icon name: 		computer-vm 
Chassis: 		        vm 
Machine ID: p		878jsdn76f7sedxshdncsdf878fwe87j
Boot ID: 		        gvxian8972hvbfv3gdg3c1cgf2fh3ghg44
Virtualization: 		kvm 
Operating System: 	Ubuntu 18.04.4 LTS 
Kernel:			Linux 5.0.0-1031-gcp 
Architecture: 		x86-64
